// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbPguKOd1ahIWG-KoxusLqJ1hTJKGsxOc',
    appId: '1:628420378856:web:9b106cba46ee2c2dfcc95d',
    messagingSenderId: '628420378856',
    projectId: 'food-go-17a5d',
    authDomain: 'food-go-17a5d.firebaseapp.com',
    databaseURL: 'https://food-go-17a5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'food-go-17a5d.firebasestorage.app',
    measurementId: 'G-6BJ4Q1XRNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr9eK2rGlAGrKwWLYSIvdmrzWJp74ebQo',
    appId: '1:628420378856:android:bf74e9666cae29b1fcc95d',
    messagingSenderId: '628420378856',
    projectId: 'food-go-17a5d',
    databaseURL: 'https://food-go-17a5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'food-go-17a5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8IeOnh7Rj8XWSXR7ZZMSu-OHZ0XktoU0',
    appId: '1:628420378856:ios:b4caaa2f7b9233f6fcc95d',
    messagingSenderId: '628420378856',
    projectId: 'food-go-17a5d',
    databaseURL: 'https://food-go-17a5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'food-go-17a5d.firebasestorage.app',
    iosBundleId: 'com.example.feFoodGoPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8IeOnh7Rj8XWSXR7ZZMSu-OHZ0XktoU0',
    appId: '1:628420378856:ios:b4caaa2f7b9233f6fcc95d',
    messagingSenderId: '628420378856',
    projectId: 'food-go-17a5d',
    databaseURL: 'https://food-go-17a5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'food-go-17a5d.firebasestorage.app',
    iosBundleId: 'com.example.feFoodGoPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbPguKOd1ahIWG-KoxusLqJ1hTJKGsxOc',
    appId: '1:628420378856:web:bd2c4a2fa1ac844efcc95d',
    messagingSenderId: '628420378856',
    projectId: 'food-go-17a5d',
    authDomain: 'food-go-17a5d.firebaseapp.com',
    databaseURL: 'https://food-go-17a5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'food-go-17a5d.firebasestorage.app',
    measurementId: 'G-XDGSBQY42N',
  );
}
